// ============ 实战工作流：14 步 ============
export const WF_BAND = { main: 66, done: 116, search: 166, prio: 220, export: 272, hotfix: 322 }
export const WF_COL = (c) => 72 + c * 40.5
export const WF_FILL = { main: '#5F5E5A', merge: '#5F5E5A', done: '#1D9E75', search: '#7F77DD', prio: '#D85A30', export: '#378ADD', fix: '#639922', revert: '#BA7517', bad: '#E24B4A' }

export const WF_NODES = [
  { id: 'C0', band: 'main', col: 0, cat: 'main', rev: 1 },
  { id: 'C1', band: 'main', col: 1, cat: 'main', tag: 'v1.0', rev: 1 },
  { id: 'D1', band: 'done', col: 2, cat: 'done', rev: 2 },
  { id: 'S1', band: 'search', col: 2, cat: 'search', rev: 2 },
  { id: 'P1', band: 'prio', col: 2, cat: 'prio', rev: 2 },
  { id: 'P2', band: 'prio', col: 3, cat: 'bad', rev: 3 },
  { id: 'M1', band: 'main', col: 4, cat: 'merge', rev: 5 },
  { id: 'C2', band: 'main', col: 5, cat: 'bad', rev: 6 },
  { id: 'R1', band: 'main', col: 6, cat: 'revert', rev: 7 },
  { id: 'P1r', band: 'prio', col: 7, cat: 'prio', rev: 8 },
  { id: 'S1c', band: 'prio', col: 8, cat: 'search', rev: 9 },
  { id: 'M2', band: 'main', col: 9, cat: 'merge', tag: 'v2.0', rev: 10 },
  { id: 'E1', band: 'export', col: 10, cat: 'export', rev: 11 },
  { id: 'F1', band: 'hotfix', col: 11, cat: 'fix', rev: 12 },
  { id: 'M3', band: 'main', col: 12, cat: 'merge', tag: 'v2.0.1', rev: 13 },
  { id: 'E2', band: 'export', col: 13, cat: 'export', rev: 14 },
  { id: 'M4', band: 'main', col: 14, cat: 'merge', tag: 'v2.1', rev: 14 },
]

export const WF_EDGES = [
  ['C0', 'C1', 'n', 1], ['C1', 'D1', 'b', 2], ['C1', 'S1', 'b', 2], ['C1', 'P1', 'b', 2],
  ['P1', 'P2', 'n', 3], ['C1', 'M1', 'n', 5], ['D1', 'M1', 'm', 5], ['M1', 'C2', 'n', 6],
  ['C2', 'R1', 'n', 7], ['R1', 'P1r', 'b', 8], ['P1', 'P1r', 'replay', 8],
  ['P1r', 'S1c', 'n', 9], ['S1', 'S1c', 'copy', 9], ['R1', 'M2', 'n', 10], ['S1c', 'M2', 'm', 10],
  ['M2', 'E1', 'b', 11], ['M2', 'F1', 'b', 12], ['M2', 'M3', 'n', 13], ['F1', 'M3', 'm', 13],
  ['E1', 'E2', 'n', 14], ['M3', 'M4', 'n', 14], ['E2', 'M4', 'm', 14],
]

export const WF_LABELS = { main: 'main', done: 'done', search: 'search', prio: 'priority', export: 'export', hotfix: 'hotfix' }

export const WF_STEPS = [
  { t: '起步：首次提交与第一版', head: 'HEAD → main', tag: 'v1.0', focus: 'C1',
    cmd: 'git init\ngit add . && git commit -m "feat: 核心功能"\ngit tag v1.0',
    what: '两次提交把项目推到可用状态，给这次提交打上 tag v1.0，作为一个里程碑。',
    cl: '提交 = 快照', cc: '每次 commit 都是整个项目在那一刻的完整快照；tag 只是钉在某次提交上的一个名字。', color: '#5F5E5A',
    model: 'main 是一个指针，每提交一次它就自动前移一格。' },
  { t: '开三条分支，并行开发下一版', head: 'HEAD → feature/priority', tag: 'v1.0', focus: 'P1',
    cmd: 'git switch -c feature/done\ngit switch -c feature/search main\ngit switch -c feature/priority main',
    what: '从 v1.0 拉出三条分支，三件事互不阻塞地同时推进——这就是"多支线推进一个 main"的起点。',
    cl: '分支 = 可移动的指针', cc: '分支只是一个指向某次提交的轻量指针，开分支几乎零成本，所以放心多开。', color: '#1D9E75',
    model: '此刻三条分支都指向 C1；HEAD 跟着你 switch 到的那条分支走。' },
  { t: '一个想法写错了（本地 WIP）', head: 'HEAD → feature/priority', tag: 'v1.0', focus: 'P2',
    cmd: 'git commit -m "按优先级排序（思路错误）"',
    what: 'priority 上提交了一版排序，但用字典序排是错的。关键点：它还没 push，只在你本地。',
    cl: '不是所有提交都得留下', cc: '本地、未共享的提交是"草稿"，可以安全地重写或删除，不会影响任何人。', color: '#E24B4A',
    model: 'HEAD 和 feature/priority 一起指向了这个坏提交 P2。' },
  { t: '回退①·reset：抹掉本地提交', head: 'HEAD → feature/priority', tag: 'v1.0', focus: 'P2',
    cmd: 'git reset --hard HEAD~1',
    what: '因为 P2 没共享出去，直接用 reset 把分支指针挪回 P1，坏提交从历史里消失（仍能在 reflog 找回）。',
    cl: 'reset = 移动分支指针', cc: '--hard 会连工作区一起重置、丢掉未保存改动，威力大、慎用；只对"私有、未推送"的提交这么干。', color: '#BA7517',
    model: '指针往回挪一格，P2 变成没人引用的悬空提交。' },
  { t: '合并第一条分支', head: 'HEAD → main', tag: 'v1.0', focus: 'M1',
    cmd: 'git switch main\ngit merge --no-ff feature/done',
    what: 'feature/done 验收通过，合回 main。--no-ff 强制生成一个合并提交，保留"这是一次完整特性合入"的痕迹。',
    cl: 'merge = 两条线汇合', cc: '--no-ff 让分支历史在图上清晰可见；合并提交 M1 有两个父：原 main 和 feature/done。', color: '#5F5E5A',
    model: 'main 前移到合并提交 M1。' },
  { t: '主干上线了一个坏提交', head: 'HEAD → main', tag: 'v1.0', focus: 'C2',
    cmd: 'git commit -m "自动保存到磁盘"   # 已 push 给团队',
    what: '自动保存功能有 bug，而且已经 push、别人已经基于它继续工作了。这就不能再 reset 了。',
    cl: '共享历史 ≠ 本地草稿', cc: '一旦推送出去、别人拉过，重写这段历史会让所有人的仓库错乱。', color: '#E24B4A',
    model: 'main 前移到 C2；这次"反悔"必须换一种安全方式。' },
  { t: '回退②·revert：对共享历史的正确回退', head: 'HEAD → main', tag: 'v1.0', focus: 'R1',
    cmd: 'git revert HEAD',
    what: 'revert 不删历史，而是生成一个"反向提交"R1 来抵消 C2 的改动。队友 pull 一下就同步了。',
    cl: 'revert = 用新提交抵消旧提交', cc: '历史只增不减，这正是协作安全的关键。口诀：私有用 reset，公开用 revert。', color: '#BA7517',
    model: 'C2 仍留在历史里（图上仍是红的），R1 抵消了它的效果。' },
  { t: '交叉①·rebase：把分支挪到最新主干', head: 'HEAD → feature/priority', tag: 'v1.0', focus: 'P1r',
    cmd: 'git switch feature/priority\ngit rebase main\n# 解决 notes.py 冲突后\ngit add notes.py && git rebase --continue',
    what: 'main 已经前进，priority 还基于老的 C1。rebase 把 priority 的提交"摘下来、重新接到最新 main 上"；它和 feature/done 改了同一文件 → 冲突，手动合并后 continue。',
    cl: 'rebase = 换地基', cc: '把提交复制、重放到新基底，得到线性干净的历史。冲突 = git 不敢替你猜，把决定权交还给你。', color: '#D85A30',
    model: '旧 P1 被废弃（虚线灰），新 P1′ 是它的副本，父变成了 R1。' },
  { t: '交叉②·cherry-pick：摘别人分支的一个提交', head: 'HEAD → feature/priority', tag: 'v1.0', focus: 'S1c',
    cmd: 'git cherry-pick <feature/search 的那个提交>',
    what: 'priority 现在需要 search 功能，但不想把整条 search 分支都合进来——只把那一个提交"摘"过来。',
    cl: 'cherry-pick = 复制单个提交', cc: '精准搬运一个提交到当前分支，常用于把某个修复补丁回合到别的分支。', color: '#7F77DD',
    model: 'S1′ 是 search 那个提交的副本；原提交在 search 分支上仍然好好的。' },
  { t: '合并发布 v2.0', head: 'HEAD → main', tag: 'v2.0', focus: 'M2',
    cmd: 'git switch main\ngit merge --no-ff feature/priority\ngit tag v2.0',
    what: 'priority（含优先级 + 摘来的 search）合回 main，打 v2.0。两条并行支线终于汇成下一个版本。',
    cl: '多支线 → 一个 main → 下一版', cc: '这就是日常迭代的主循环：并行开发、各自验收、汇入主干、发版。', color: '#5F5E5A',
    model: 'M2 把两条历史正式并轨。' },
  { t: '开始一个长周期特性', head: 'HEAD → feature/export', tag: 'v2.0', focus: 'E1',
    cmd: 'git switch -c feature/export\ngit commit -m "wip(export): 导出骨架"',
    what: '开始做导出功能，写到一半（WIP），工作区里全是没完成的代码。',
    cl: '做到一半被打断', cc: '真实开发里这太常见了——下面看 git 怎么优雅处理"正干着活，线上突然出事"。', color: '#378ADD',
    model: 'HEAD 在 feature/export，工作区是"脏"的半成品。' },
  { t: 'worktree：并行热修复线上 bug', head: 'HEAD → hotfix/crash（独立工作树）', tag: 'v2.0', focus: 'F1',
    cmd: 'git worktree add -b hotfix/crash ../hotfix-crash main\ncd ../hotfix-crash   # 另一个目录，干净的 main\n# 修复并提交',
    what: '线上崩溃报告来了！传统做法得先 stash 半成品再切分支。worktree 直接在另一个目录里 checkout 出 main，热修复和你的半成品同时存在、互不干扰。',
    cl: 'worktree = 一仓库多目录', cc: '同一个 .git，多个工作目录，各自挂一条分支，物理隔离地并行——这是高手处理打断的标准姿势。', color: '#639922',
    model: '两个目录共享同一个 .git；feature/export 的半成品一个字都没被动过。' },
  { t: '合并热修复，补丁发版', head: 'HEAD → main', tag: 'v2.0.1', focus: 'M3',
    cmd: 'cd ../notes-app && git switch main\ngit merge --no-ff hotfix/crash\ngit tag v2.0.1\ngit worktree remove ../hotfix-crash',
    what: '热修复合回 main，打补丁版 v2.0.1，再删掉这个临时工作树，干净利落。',
    cl: '线上救火的标准流程', cc: '独立小分支 + 独立 worktree + 补丁版号，修完即弃，不污染正在进行的开发。', color: '#639922',
    model: 'main 前移到 v2.0.1；主线 export 仍原封不动等你回去。' },
  { t: '特性零干扰完成，发布 v2.1', head: 'HEAD → main', tag: 'v2.1', focus: 'M4',
    cmd: 'git switch feature/export\ngit commit -m "feat(export): 完成导出"\ngit switch main && git merge --no-ff feature/export\ngit tag v2.1',
    what: '回到 feature/export 接着写完、合并、发 v2.1。因为刚才用了 worktree，这条线全程零干扰。',
    cl: '你已经走通了完整工作流', cc: '并行分支 / reset / revert / rebase / cherry-pick / worktree —— 这就是日常 git 的全貌。', color: '#D85A30',
    model: '"分支是指针、提交是快照、HEAD 是你现在站在哪里"——这套心智模型你已经走了一整遍。' },
]

// ============ 概念协作图 ============
export const CM_FOCUS = {
  work: ['work', 'addE', 'index', 'pullE', 'remote'],
  index: ['index', 'addE', 'work', 'commitE', 'c2'],
  commit: ['c1', 'c2', 'commitE', 'index', 'parent'],
  branch: ['main', 'mainref', 'c2', 'head', 'headE', 'pushE', 'pullE', 'remote'],
  head: ['head', 'headE', 'main'],
  tag: ['tag', 'tagE', 'c1'],
  remote: ['remote', 'pushE', 'pullE', 'main', 'work'],
}
export const CM_ALL = ['work', 'index', 'addE', 'c1', 'c2', 'parent', 'commitE', 'main', 'mainref', 'head', 'headE', 'tag', 'tagE', 'remote', 'pushE', 'pullE']
export const CM_NOTE = {
  all: { t: 'git 的全部协作 = 指针与快照在互相指、互相移动', b: '点下面任一概念，看它如何与其他概念协作、用什么命令。记住三件事：① 提交是不可变快照，靠 parent 指针串成历史；② 分支 / HEAD / tag 都只是"指向某个提交"的指针；③ 工作区 / 暂存区 / 远程，是文件流转的三个场所。', c: [] },
  work: { t: '工作区 (Working Directory)', b: '你直接编辑文件的地方。改动停在这里时 git 还没"记账"。它把选中的改动交给暂存区（git add）；用 git restore 丢弃改动；远程拉下来的更新最终也落回这里（git pull）。', c: ['git status', 'git add <file>', 'git restore <file>', 'git diff'] },
  index: { t: '暂存区 (Index / Staging)', b: '"下一次提交的预演台"。你挑哪些改动进暂存区，就决定了下次 commit 包含什么——这让你能把一团改动拆成干净的几次提交。git add 进、git restore --staged 出、git commit 把它打包成一个快照。', c: ['git add <file>', 'git restore --staged <file>', 'git diff --staged', 'git commit -m "..."'] },
  commit: { t: '提交 commit （快照）', b: '项目某一刻的不可变快照，并带一个指向父提交的指针。无数提交靠 parent 指针首尾相连，就构成了"历史"。提交由暂存区经 git commit 产生；分支、HEAD、tag 本质都只是"指向某个提交"的指针。', c: ['git commit', 'git log --oneline --graph', 'git show <hash>'] },
  branch: { t: '分支 branch （会动的指针）', b: '指向某个提交的轻量指针。你在哪条分支上提交，它就跟着自动前移——这是并行开发的基础。新建用 git switch -c，汇合用 git merge / rebase，上传用 git push。', c: ['git branch', 'git switch -c <name>', 'git merge <branch>', 'git rebase <branch>'] },
  head: { t: 'HEAD （你站在哪）', b: '指向"你当前所在的分支"（再由分支指到某个提交）。它回答"我现在在哪条线上"。git switch 改变的就是 HEAD；你一提交，HEAD 和它指向的分支一起前移一格。', c: ['git switch <branch>', 'git checkout <hash>', 'git log HEAD'] },
  tag: { t: '标签 tag （钉死的书签）', b: '钉在某个提交上、永不移动的名字（如 v1.0），用来标记发布里程碑。和分支的唯一区别：分支随提交移动，tag 不动。', c: ['git tag v1.0', 'git tag', 'git checkout v1.0'] },
  remote: { t: '远程仓库 remote （团队共享）', b: '团队共享的那份仓库（GitHub 等）。本地有个 origin/main 镜像指针记录"远程到哪了"。git push 上传本地新提交；git fetch 只更新这个镜像、不动工作区；git pull = fetch + merge，把远程改动真正合进你的分支和工作区。', c: ['git remote -v', 'git push', 'git fetch', 'git pull'] },
}
export const CM_CHIPS = [['all', '全部'], ['work', '工作区'], ['index', '暂存区'], ['commit', '提交 commit'], ['branch', '分支 branch'], ['head', 'HEAD'], ['tag', '标签 tag'], ['remote', '远程 remote']]

// ============ 测验题 ============
export const QUIZZES = {
  basics: [
    { q: '你刚 commit 完，发现提交信息打错了字，而且这个提交还没 push。最干净的做法是？',
      o: [{ t: 'git commit --amend 改掉信息', c: true }, { t: 'git revert HEAD', c: false }, { t: '再提交一次写"修正上一条信息"', c: false }],
      e: '未推送的提交可以安全重写。--amend 直接修补上一次提交（改信息或补文件）。revert 是给已共享、不能重写的提交用的。' },
    { q: 'git add 这个命令，本质是把改动从哪里搬到哪里？',
      o: [{ t: '工作区 → 暂存区', c: true }, { t: '暂存区 → 本地仓库', c: false }, { t: '本地仓库 → 远程', c: false }],
      e: 'add 把工作区的改动登记进暂存区；commit 才把暂存区固化成提交；push 才上传到远程。' },
  ],
  undo: [
    { q: '一个有 bug 的提交已经 push 给团队、别人也基于它工作了。你应该用？',
      o: [{ t: 'git revert（生成反向提交抵消）', c: true }, { t: 'git reset --hard（指针退回）', c: false }, { t: 'git rebase 把它删掉', c: false }],
      e: '已共享的历史不能重写。revert 用一个新的"反向提交"抵消它，历史只增不减，队友 pull 即可同步。reset/rebase 会改写历史，只适合私有、未推送的提交。' },
    { q: '你 git reset --hard 把一个提交丢了，过会儿后悔了。还能救回来吗？',
      o: [{ t: '能，git reflog 找到 hash 再 reset 回去', c: true }, { t: '不能，--hard 是永久删除', c: false }, { t: '只能去 GitHub 重新下载', c: false }],
      e: '被 reset 丢掉的提交会进 reflog，默认保留约 90 天。git reflog 找到那个 hash，再 git reset --hard <hash> 即可救回。' },
    { q: 'reset 和 rebase 都会"改写历史"，使用它们的共同前提是？',
      o: [{ t: '被操作的提交没 push、或只有你自己在用', c: true }, { t: '必须先 git pull', c: false }, { t: '团队所有人都在线', c: false }],
      e: '黄金法则：不要重写已经 push 且别人在用的历史。自己的私有分支随便 reset / rebase。' },
  ],
  remote: [
    { q: 'git fetch 和 git pull 的区别是？',
      o: [{ t: 'fetch 只下载更新不合并；pull = fetch + merge 会改你的工作区', c: true }, { t: '完全一样', c: false }, { t: 'fetch 上传，pull 下载', c: false }],
      e: 'fetch 只更新本地的 origin/* 镜像指针，安全、不动你的工作。pull 在 fetch 之后还自动 merge（或 rebase）进当前分支。' },
    { q: '多人协作时，为了让历史更线性、少一堆 merge 提交，拉取常用？',
      o: [{ t: 'git pull --rebase', c: true }, { t: 'git pull --force', c: false }, { t: 'git push --rebase', c: false }],
      e: 'pull --rebase 把你本地的提交"重放"到远程最新提交之上，避免每次拉取都产生一个 merge 提交，历史更干净。' },
  ],
  conflict: [
    { q: '合并时出现冲突，git 自动帮你选了一边的代码吗？',
      o: [{ t: '不会，它把两边都标出来，让你决定', c: true }, { t: '会，自动选较新的那次提交', c: false }, { t: '会，自动选 main 上的版本', c: false }],
      e: '冲突恰恰是 git 不敢替你猜的地方：同一处两个人都改了。它用 <<<<<<< ======= >>>>>>> 把两边都标出来，把选择权交给你。' },
    { q: '解决完冲突文件后，继续合并的正确动作是？',
      o: [{ t: 'git add <文件> 标记已解决，再 commit 或 rebase --continue', c: true }, { t: '直接 git push', c: false }, { t: '什么都不用做，保存文件即可', c: false }],
      e: '改好文件、删掉冲突标记后，要用 git add 告诉 git"这个冲突我处理好了"；merge 场景接着 git commit，rebase 场景用 git rebase --continue。' },
  ],
  stash: [
    { q: '你正改到一半（工作区是脏的），突然要切到别的分支救急。最轻量的做法是？',
      o: [{ t: 'git stash 把改动收进抽屉，切走，回来再 git stash pop', c: true }, { t: '随便 commit 一个"临时"提交', c: false }, { t: '把文件复制到别处备份', c: false }],
      e: 'stash 把未提交改动（工作区+暂存区）打包压进一个栈，让工作区瞬间变干净，便于切分支；回来 git stash pop 取回。比留一个垃圾提交干净得多。' },
    { q: 'git stash pop 和 git stash apply 的区别？',
      o: [{ t: 'pop 取回并从栈里删除；apply 取回但保留在栈里', c: true }, { t: '完全一样', c: false }, { t: 'pop 只取暂存区，apply 只取工作区', c: false }],
      e: 'apply 取回改动但 stash 仍留在栈里（可重复应用到多个分支）；pop = apply + drop，取回后顺手把这条 stash 删掉。' },
  ],
}
